### ISSUE TITLE
Missing dollarsign on script

### ISSUE THREAD

**Issue by boyobejamin** [zorglube/freenas-iocage-movienight#1]
Hey there, in the `movienight-jail.sh` script, should the following line have `$` added?

- `if ! iocage exec ${JAIL_NAME} chown {UID}:{GID} ${MN_LOG_FILE} `
+ `if ! iocage exec ${JAIL_NAME} chown ${UID}:${GID} ${MN_LOG_FILE} `

**Comment by zorglube** [comment]
Seems you're right. Did you made some test ?

**Comment by boyobejamin** [comment]
Yeah, the installation failed without it because it wasn't able to resolve to a good GID/UID.

I'm going to look at the start script too today. There are some similar small things to be fixed to get that rocking. 

I'm super excited to have this easily working on my FreeNAS box!

**Comment by zorglube** [comment]
Thank you ! 

Do not hesitate to ask questions and make some feedback, I  need some to improve. 

See ya, 
Zorglube

**Comment by zorglube** [comment]
Hey @boyobejamin , did you made some tests ?

**Comment by boyobejamin** [comment]
Yeah, here's a PR where I've made other changes to get it working. Everything currently deploys successfully with the following modifications.

https://github.com/zorglube/freenas-iocage-movienight/pull/3

I was going to turn this into a FreeNAS plugin but time got away from me. Hopefully this helps others!

**Comment by zorglube** [comment]
> I was going to turn this into a FreeNAS plugin but time got away from me. Hopefully this helps others!

I also want to do this, maybe we should work together ?

**Comment by boyobejamin** [comment]
Totally! I'd be down for that. I'm busy this weekend but will make time this week to research the effort. A cursory glance shows it's not a huge lift to make it a plugin.

**Comment by zorglube** [comment]
Their at least two way to make an FreeNAS/TrueNAS plugin. 
 - We can make an TrueNAS plugin with a lot of script into the `post_install.sh`. Like: Create Jail, and post install contain install GoLang, Clone repo, Compile and run and so on. 
 - We can create an BSD Port of MovieNight then an TrueNAS plugin. This solution seems to be better. 
 
Do you have some idea ? Point of view ?
