### ISSUE TITLE
Script fails - 12.2-RC3 was not found!, not running after install

### ISSUE THREAD

**Issue by csjjpm** [zorglube/freenas-iocage-movienight#8]
Hi,
  I have TrueNAS-12.0-RELEASE and in the shell it says it is FreeBSD 12.2-RC3 7c4ec6ff02c(HEAD) TRUENAS

When try to run the setup script I get an error and it fails.  Any ideas how I fix this?

```
root@freenas:/mnt/WD20EARS/iocage/jails/freenas-iocage-movienight # ./movienight-jail.sh
jail 'movienight' not found!
JAIL_INTERFACES not set, defaulting to: vnet0:bridge0
12.2-RC3 was not found!
Failed to create jail
root@freenas:/mnt/WD20EARS/iocage/jails/freenas-iocage-movienight #

```

Thank you
Paul

**Comment by csjjpm** [comment]
Is it something to do with line 51?
RELEASE=$(freebsd-version | sed "s/STABLE/RELEASE/g" | sed "s/-p[0-9]*//")

**Comment by csjjpm** [comment]
I've commented out the check and used the defined var
```
#RELEASE=$(freebsd-version | sed "s/STABLE/RELEASE/g" | sed "s/-p[0-9]*//")
# Arbitrary selection of an version of the `iocage`
RELEASE=12.2-RELEASE
```

**Comment by csjjpm** [comment]
It has installed a JAIL and I can scan it on my network but there is no service running, I've restarted the JAIL but when I go to x.x.x.x:8089 the browser cant connect

**Comment by csjjpm** [comment]
Sorry to keep spamming this.  I've tried a service restart in the jail and it says the service is running but there is a warning


```
root@movienight:/usr/local/movienight # service movienight start
/usr/local/etc/rc.d/movienight: WARNING: no shebang line in /usr/local/movienight/MovieNight
daemon: process already running, pid: 27722
```

**Comment by zorglube** [comment]
No problems, I'll check your comments this evening.

**Comment by csjjpm** [comment]
I'll be online tonight (GMT) so I'll try and catch up with you then.  Thank you

**Comment by zorglube** [comment]
Ok, I'm into GMT+1.

**Comment by zorglube** [comment]
Hello, 

The Script ins still in progress. As answer for your questions : 
 - This line `RELEASE=$(freebsd-version | sed "s/STABLE/RELEASE/g" | sed "s/-p[0-9]*//")` intent to get the running version of FreeNAS/TrueNAS by transforming `12.2-RELEASE-p2` into `12.2-RELEASE` for example; BUT ! You're running an `12.2-RC3` witch isn't handled by the script. So you were right when you commented the line 51 and uncomment 53. 
 - About the `daemon` part.  check the running process into the Jail you should see `daemon` and `MovieNight` at least. If MovieNight hasn't started you should check the starting log into `/var/log/movienight.log` and check MovieNight log file from the setting file `/usr/local/movienight/settings.json`. For the question about `setting.json` check [MovieNight](https://github.com/zorglube/MovieNight)


By the way the `service`command have many options : ` [fast|force|one|quiet](start|stop|restart|rcvar|enable|disable|delete|enabled|describe|extracommands|reload|configtest|upgrade|gracefulstop|status|poll)` it may be usefull. 

Please tell me if I helped you or how I can improve my script. 
See ya, 
Z

**Comment by csjjpm** [comment]
Hi,
 sorry I'm not the best on BSD.  I used top and it listed processes.  MovieNight wasn't listed but then appeared for a second and went again.  I waited but it didnt come back.  I quit top and ran top again and it did the same thing.  Maybe after 30 seconds MovieNight appeared and then went.
There is only one daemon called nanslp (it is also a cron)

**Comment by csjjpm** [comment]
The log file has this
```
Log file: thelog.log
Error loading settings: Unable to load settings: Unable to setup logger: Unable>
```

**Comment by csjjpm** [comment]
I can't stop movienight as I get this error
```
root@movienight:~ # service movienight stop
/usr/local/etc/rc.d/movienight: WARNING: no shebang line in /usr/local/movienight/MovieNight
```

**Comment by zorglube** [comment]
> Hi,
> sorry I'm not the best on BSD. I used top and it listed processes. MovieNight wasn't listed but then appeared for a second and went again. I waited but it didnt come back. I quit top and ran top again and it did the same thing. Maybe after 30 seconds MovieNight appeared and then went.
> There is only one daemon called nanslp (it is also a cron)

Ok, the mean MovieNight have some problems to start and the `deamon` witch is the manager try to restart it. 

Try : 
 - Stop the `daemon` : `service movienight stop` or `service movienight stop force` 
 - Check the content of `/var/log/movienight.log` searching for error 
 - Check the configuration of MovieNight `/usr/local/movienight/settings.json` with the doc 
 - Try start MN `service movienight start`

**Comment by zorglube** [comment]
> The log file has this
> 
> ```
> Log file: thelog.log
> Error loading settings: Unable to load settings: Unable to setup logger: Unable>
> ```

Instead of `thelog.log` is advise you to put the log file at an standard log position like `/var/log/movienight.log`

**Comment by zorglube** [comment]
> I can't stop movienight as I get this error
> 
> ```
> root@movienight:~ # service movienight stop
> /usr/local/etc/rc.d/movienight: WARNING: no shebang line in /usr/local/movienight/MovieNight
> ```

Try `kill -9 PROCESS_PID` with deamon PID and MovieNight PID if available.

**Comment by csjjpm** [comment]
Looks like it is a permissions issue

Log file: thelog.log
Error loading settings: Unable to load settings: Unable to setup logger: Unable to open log file for writing: open thelog.log: permission denied

**Comment by zorglube** [comment]
> Looks like it is a permissions issue
> 
> Log file: thelog.log
> Error loading settings: Unable to load settings: Unable to setup logger: Unable to open log file for writing: open thelog.log: permission denied

Yes you're right check [here ](https://github.com/zorglube/freenas-iocage-movienight/issues/8#issuecomment-774773487)

**Comment by csjjpm** [comment]
I've amended the settings.json file and restarted the jail but the log file hasn't been created in /var/log
```
{
        "LogFile": "/var/log/thelog.log",
  
```

**Comment by zorglube** [comment]
Maybe, create it manually.

**Comment by csjjpm** [comment]
New issue (weird?)

```
Log file: /var/log/thelog.log
Error loading settings: Unable to load settings: Unable to setup logger: Unable to open log file for writing: open /var/log/thelog.log: permission denied
```

**Comment by csjjpm** [comment]
Have created it manually and chmod 777


[INFO] 2021/02/07 22:01:13 RateLimitChat: 1ns
[INFO] 2021/02/07 22:01:13 RateLimitNick: 300ns
[INFO] 2021/02/07 22:01:13 RateLimitColor: 60ns
[INFO] 2021/02/07 22:01:13 RateLimitAuth: 5ns
[DEBUG] 2021/02/07 22:01:13 finding emotes in "/usr/local/movienight/static/emo>
[INFO] 2021/02/07 22:01:13 Found 0 emotePNGs
[INFO] 2021/02/07 22:01:13 Found 0 emoteGIFs
[INFO] 2021/02/07 22:01:13 processEmoteDir: 0
[INFO] 2021/02/07 22:01:13 Loaded 0 emotes
[INFO] 2021/02/07 22:01:13 Stream key:  ALongStreamKey
[INFO] 2021/02/07 22:01:13 Admin passw
[INFO] 2021/02/07 22:01:13 HTTP server listening on:  :8089
[INFO] 2021/02/07 22:01:13 RTMP server listening on:  :1935
[I

**Comment by csjjpm** [comment]
Server is running NOW!!  whoop whoop

**Comment by csjjpm** [comment]
Now have to work out how to use the server :-)
thank you for your help

**Comment by zorglube** [comment]
\o/ Congrats !!! 

I recommend [OBS ](https://obsproject.com) to emit the stream AND i recommend you to join [Zorchenhimer](https://discord.gg/F2VSgjJ) Discord he stream often or [Paris Cinema Club](https://www.facebook.com/ParisCSCinemaClub) we're streaming every monday.

**Comment by zorglube** [comment]
> Now have to work out how to use the server :-)
> thank you for your help

you're welcome !
